#!/usr/bin/env bash
# Bash script that configures a server to the above requirements
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs.
sudo aptget -y update
sudo aptget install -y nginx
sudo service nginx start
